name: Run Bash Script

on: [push]

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permissions
      run: chmod +x ./script.sh

    - name: Run bash script
      run: ./script.sh
